/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Database;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author CSE
 */
public class JFrame_Edit_List extends javax.swing.JFrame {
    Student_List sList = new Student_List();
    int position=0; // current position of Student
    int numStudents = 0; // number of CDs in the list
    /**
     * Creates new form JFrame_Edit_List
     */
    public JFrame_Edit_List() {
        initComponents();
        deserializeCD_List();
        if(!sList.isEmpty()){
           populate_TextBoxes(sList.get(position),position+1); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Name = new javax.swing.JTextField();
        jTextField_id = new javax.swing.JTextField();
        jButton_Delete = new javax.swing.JButton();
        jButton_Update = new javax.swing.JButton();
        jButton_Add = new javax.swing.JButton();
        jButton_Next = new javax.swing.JButton();
        jButton_Prev = new javax.swing.JButton();
        jTextField_Search = new javax.swing.JTextField();
        jButton_Last = new javax.swing.JButton();
        jButton_First = new javax.swing.JButton();
        jButton_Sort = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Address = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_cgpa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Data Manipulation Form");

        jLabel1.setText("Name");

        jLabel2.setText("ID");

        jButton_Delete.setText("Delete");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });

        jButton_Update.setText("Update");
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });

        jButton_Add.setText("Add");
        jButton_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddActionPerformed(evt);
            }
        });

        jButton_Next.setText(">>");
        jButton_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NextActionPerformed(evt);
            }
        });

        jButton_Prev.setText("<<");
        jButton_Prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PrevActionPerformed(evt);
            }
        });

        jTextField_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SearchActionPerformed(evt);
            }
        });

        jButton_Last.setText(">|");
        jButton_Last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LastActionPerformed(evt);
            }
        });

        jButton_First.setText("|<");
        jButton_First.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FirstActionPerformed(evt);
            }
        });

        jButton_Sort.setText("Sort");
        jButton_Sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SortActionPerformed(evt);
            }
        });

        jLabel4.setText("Address");

        jTextField_Address.setToolTipText("");

        jLabel5.setText("CGPA");

        jTextField_cgpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_cgpaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton_First)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton_Prev)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton_Next, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton_Last))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton_Add)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton_Update)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton_Delete)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton_Sort, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                    .addComponent(jTextField_id)
                                    .addComponent(jTextField_Address)
                                    .addComponent(jTextField_cgpa))))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_cgpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_First)
                    .addComponent(jButton_Prev)
                    .addComponent(jTextField_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Next)
                    .addComponent(jButton_Last))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Add)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_Delete)
                        .addComponent(jButton_Sort)
                        .addComponent(jButton_Update)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Deserialize single Student

//Deserialize single Student List
public void deserializeCD_List(){
    
    try{
      
     FileInputStream fin = new FileInputStream("CD.ser");
     ObjectInputStream ois = new ObjectInputStream(fin);
           
     sList = (Student_List) ois.readObject();
     numStudents = sList.num_CDs();
     ois.close();
    
     //return item;
     
    }
    catch(Exception e){
     JOptionPane.showMessageDialog(null,e.getMessage());
     
    } 
   }

public void serializeCD_List(){
    
    try{
      
      FileOutputStream fout = new FileOutputStream("CD.ser");
      ObjectOutputStream oos = new ObjectOutputStream(fout);   
      oos.writeObject(sList);
      oos.close();
      //JOptionPane.showMessageDialog(null,"Successfully saved");
      
    }
    catch(Exception e){
      JOptionPane.showMessageDialog(null,e.getMessage());
    }
  }
  
private Student create_Student(){
        // Number Format try korte hobe
        if(this.jTextField_Name.getText().isEmpty()||this.jTextField_id.getText().isEmpty())
            return null;
        String Name = this.jTextField_Name.getText().trim();
        String id = this.jTextField_id.getText().trim();
        String Address = this.jTextField_Address.getText().trim();
        String cgpa = this.jTextField_cgpa.getText().trim();
        try{
            int time = Integer.parseInt(id);
//            int numTracks = Integer.parseInt(cgpa);
            double cgpa_cnt = Double.parseDouble(cgpa);
            return new Student(Name,Address,time,cgpa_cnt);
            
            
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Input integers for Time and #Tracks");
            return null;
        }
    }
    
    private void populate_TextBoxes(Student item, int pos){
        this.jTextField_Name.setText(item.getTitle());
        this.jTextField_id.setText(Integer.toString(item.getPlayingTime()));
        this.jTextField_Address.setText(item.getArtist());
        this.jTextField_cgpa.setText(Double.toString(item.getNumberOfTracks()));
        this.jTextField_Search.setText(pos+"/"+numStudents);
    }
    private void Clear_TextBoxes(){
        this.jTextField_Name.setText("");
        this.jTextField_id.setText("");
        this.jTextField_Address.setText("");
        this.jTextField_cgpa.setText("");
        this.jTextField_Search.setText("");
    }

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
        // TODO add your handling code here:
        //deserializeCD_List();
        if(!sList.isEmpty()){
            sList.deleteCD(position);
            serializeCD_List();
            numStudents--;
            if(position == numStudents)
               position-- ;
            if(sList.isEmpty())
                Clear_TextBoxes();
            else
                populate_TextBoxes(sList.get(position),position+1); 
        }
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
        Student newCD = create_Student();
        if(newCD==null)
                JOptionPane.showMessageDialog(null,"CD is not properly created");
        if(sList.Contains(newCD) && position != sList.getIndex(newCD) )
                JOptionPane.showMessageDialog(null,"CD already exists");
        if(!(newCD==null) && (!sList.Contains(newCD)) && position == sList.getIndex(newCD) )
            sList.updateCD(position,newCD);
        if(!sList.isEmpty()){
            serializeCD_List();
            //populate_TextBoxes(sList.get(position),position+1);
        }
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void jButton_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddActionPerformed
        // TODO add your handling code here:
        Student newCD = create_Student();
        if(newCD==null)
                JOptionPane.showMessageDialog(null,"CD is not properly created");
        if(sList.Contains(newCD))
                JOptionPane.showMessageDialog(null,"CD already exists");
        if(!(newCD==null) && (!sList.Contains(newCD))){
            sList.addCD(newCD);
            numStudents++;
            position = numStudents-1; // set position to last Student
            serializeCD_List();
            populate_TextBoxes(sList.get(position),position+1);
        }
    }//GEN-LAST:event_jButton_AddActionPerformed

    private void jButton_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NextActionPerformed
        // TODO add your handling code here:
       if(position<(sList.num_CDs()-1))
            position++;
        populate_TextBoxes(sList.get(position),position+1);
    }//GEN-LAST:event_jButton_NextActionPerformed

    private void jButton_PrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PrevActionPerformed
        // TODO add your handling code here:
        if(position>0)
            position--;
        populate_TextBoxes(sList.get(position),position+1);
    }//GEN-LAST:event_jButton_PrevActionPerformed

    private void jTextField_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SearchActionPerformed
        try{
            int pos = Integer.parseInt(this.jTextField_Search.getText().trim());
            if(pos>0 && pos<numStudents ){
              position = pos-1;
              populate_TextBoxes(sList.get(position),position+1);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Valid integer required");
        }

    }//GEN-LAST:event_jTextField_SearchActionPerformed

    private void jButton_LastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LastActionPerformed
        position=sList.num_CDs()-1;
        populate_TextBoxes(sList.get(position),position+1);
    }//GEN-LAST:event_jButton_LastActionPerformed

    private void jButton_FirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FirstActionPerformed
        position=0;
        populate_TextBoxes(sList.get(position),position+1);
    }//GEN-LAST:event_jButton_FirstActionPerformed

    private void jButton_SortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SortActionPerformed
        if(!sList.isEmpty()){
            sList.Sort();
            serializeCD_List();
            position = 0;
            populate_TextBoxes(sList.get(position),position+1);
        }
    }//GEN-LAST:event_jButton_SortActionPerformed

    private void jTextField_cgpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_cgpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_cgpaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Edit_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Edit_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Edit_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Edit_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Edit_List().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_First;
    private javax.swing.JButton jButton_Last;
    private javax.swing.JButton jButton_Next;
    private javax.swing.JButton jButton_Prev;
    private javax.swing.JButton jButton_Sort;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField_Address;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextField jTextField_Search;
    private javax.swing.JTextField jTextField_cgpa;
    private javax.swing.JTextField jTextField_id;
    // End of variables declaration//GEN-END:variables
}
