/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */

import java.awt.Color;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.*;
import java.util.*;



public class main_f extends javax.swing.JFrame {

    /**
     * Creates new form main_f
     */
    
    private static final String username = "root";
    private static final String password = "aZm123@#12";
    private static final String dataConn = "jdbc:mysql://localhost:3306/student_database";

    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int q,i,id,deleteitem;
    String ordr=" order by created_at asc ";
    
    public main_f() {
        initComponents();
        showDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    //_____________________________________function_______________________________
    
    public void upDateDB(){
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn,username,password);
            pst = sqlConn.prepareStatement("select * from student_database" + ordr);
            
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            q = stData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
                    RecordTable.setRowCount(0);
            while(rs.next()){
                Vector columnData = new Vector();
                for(i=1;i<=q;i++){
                    columnData.add(rs.getString("Name"));                   
                    columnData.add(rs.getString("id"));
                    columnData.add(rs.getString("address"));

                }
                RecordTable.addRow(columnData);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    
    
    public void showDB() {
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection sqlConn = DriverManager.getConnection(dataConn, username, password);
        PreparedStatement pst = sqlConn.prepareStatement("SELECT * FROM student_database"+ordr);
        
        ResultSet rs = pst.executeQuery();
        ResultSetMetaData stData = rs.getMetaData();
        
        int q = stData.getColumnCount();
        
        DefaultTableModel RecordTable = (DefaultTableModel) jTable1.getModel();
        RecordTable.setRowCount(0);
        
        while (rs.next()) {
            Vector columnData = new Vector();
            for (int i = 1; i <= q; i++) {
                columnData.add(rs.getString("Name")); 
                columnData.add(rs.getString("id")); 
                columnData.add(rs.getString("address")); 
            }
            RecordTable.addRow(columnData);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}


    
    
    
    //_____________________________________function_______________________________

    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        name_label = new javax.swing.JLabel();
        name_text_field = new javax.swing.JTextField();
        id_text_field = new javax.swing.JTextField();
        id_label = new javax.swing.JLabel();
        address_text_field = new javax.swing.JTextField();
        address_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        add_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        del_btn = new javax.swing.JButton();
        exit_btn = new javax.swing.JButton();
        reset_btn = new javax.swing.JButton();
        sort_in_style = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        bottom = new javax.swing.JButton();
        previous = new javax.swing.JButton();
        next = new javax.swing.JButton();
        top = new javax.swing.JButton();
        count_text_field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student_Management_System");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 128, 137)));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setMinimumSize(new java.awt.Dimension(500, 50));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 70));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        jLabel1.setText("Student Management System");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 8, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        name_label.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        name_label.setText("Name");

        name_text_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_text_fieldActionPerformed(evt);
            }
        });

        id_text_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_text_fieldActionPerformed(evt);
            }
        });

        id_label.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        id_label.setText("Id");

        address_text_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_text_fieldActionPerformed(evt);
            }
        });

        address_label.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        address_label.setText("Address");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id_label)
                            .addComponent(name_label))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(name_text_field, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addComponent(id_text_field)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(address_label)
                        .addGap(18, 18, 18)
                        .addComponent(address_text_field)))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_label)
                    .addComponent(name_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_label)
                    .addComponent(id_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address_label)
                    .addComponent(address_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 450, 180));

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Id", "Address"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 430, 310));

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        add_btn.setText("Add");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        del_btn.setText("Delete");
        del_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_btnActionPerformed(evt);
            }
        });

        exit_btn.setText("Exit");
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });

        reset_btn.setText("Reset");
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });

        sort_in_style.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Name", "Id" }));
        sort_in_style.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sort_in_styleActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(add_btn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(update_btn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(del_btn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(exit_btn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(reset_btn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(sort_in_style, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(del_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exit_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reset_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(sort_in_style, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(add_btn)
                .addGap(18, 18, 18)
                .addComponent(update_btn)
                .addGap(18, 18, 18)
                .addComponent(del_btn)
                .addGap(18, 18, 18)
                .addComponent(sort_in_style, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(reset_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exit_btn)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jPanel1.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 100, 310));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 270, 70));

        bottom.setText(">>");
        bottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottomActionPerformed(evt);
            }
        });

        previous.setText(">");
        previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousActionPerformed(evt);
            }
        });

        next.setText("<");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        top.setText("<<");
        top.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topActionPerformed(evt);
            }
        });

        count_text_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        count_text_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                count_text_fieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(top, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(count_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(previous, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(bottom, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(next)
                    .addComponent(top)
                    .addComponent(count_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bottom)
                    .addComponent(previous))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 430, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1042, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void name_text_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_text_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_text_fieldActionPerformed

    private void id_text_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_text_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_text_fieldActionPerformed

    private void address_text_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_text_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_text_fieldActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
         try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn,username,password);
            pst = sqlConn.prepareStatement("update student_database set Name =?, address=? where id=?");
 
            pst.setString(1,name_text_field.getText());
            pst.setString(3,id_text_field.getText());
            pst.setString(2,address_text_field.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record updated");
            
            upDateDB();
            
            
        
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_update_btnActionPerformed
    private JFrame frame;
    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit","Student Management System",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_exit_btnActionPerformed

    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
        // TODO add your handling code here:
        name_text_field.setText("");
        id_text_field.setText("");
        address_text_field.setText("");
        count_text_field.setText("");
       jTable1.clearSelection();
        
    }//GEN-LAST:event_reset_btnActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        // TODO add your handling code here:
         try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn,username,password);
            pst = sqlConn.prepareStatement("insert into student_database(Name,id,address)value(?,?,?)");
        
            pst.setString(1,name_text_field.getText());
            pst.setString(2,id_text_field.getText());
            pst.setString(3,address_text_field.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Added");
            
            upDateDB();
            
            
        
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);

        }
        
        
        
    }//GEN-LAST:event_add_btnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
      
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
             int SelectedRows =jTable1.getSelectedRow();
        name_text_field.setText(RecordTable.getValueAt(SelectedRows, 0).toString());
        id_text_field.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
        address_text_field.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
        
      
        count_text_field.setText(String.valueOf(SelectedRows + 1) + " / " + RecordTable.getRowCount());
             
             
             
    }//GEN-LAST:event_jTable1MouseClicked

    private void del_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_btnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        try{
            id = Integer.parseInt(RecordTable.getValueAt(SelectedRows,1).toString());
            
            deleteitem = JOptionPane.showConfirmDialog(null,"Confirm if you want to delete item","warning",JOptionPane.YES_NO_OPTION) ;
            
            if(deleteitem == JOptionPane.YES_OPTION){
                Class.forName("com.mysql.cj.jdbc.Driver");
                sqlConn = DriverManager.getConnection(dataConn,username,password);
                pst = sqlConn.prepareStatement("delete from student_database where id = ?");
                
                pst.setInt(1, id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"Record Updated");
                upDateDB();
                
                name_text_field.setText("");                
                id_text_field.setText("");
                address_text_field.setText("");
                count_text_field.setText("");

            }
               
            
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_del_btnActionPerformed

    private void bottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottomActionPerformed
        // TODO add your handling code here:
        if(row_is_selected == false){
            model = (DefaultTableModel) jTable1.getModel();
            row_is_selected = true;
        }
        index=model.getRowCount()-1;
        if(model.getRowCount() > 0){
            
            jTable1.setRowSelectionInterval(index, index);
            jTable1.setSelectionBackground(Color.BLACK);
        int SelectedRows = index;
        name_text_field.setText(model.getValueAt(SelectedRows, 0).toString());
        id_text_field.setText(model.getValueAt(SelectedRows, 1).toString());
        address_text_field.setText(model.getValueAt(SelectedRows, 2).toString());
         count_text_field.setText(String.valueOf(SelectedRows + 1) + " / " + model.getRowCount());
          
        }
    }//GEN-LAST:event_bottomActionPerformed

    boolean row_is_selected = false;
    int index;
    DefaultTableModel model;
    
    private void previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousActionPerformed
        // TODO add your handling code here:
        
        if(row_is_selected == false){
            model = (DefaultTableModel) jTable1.getModel();
            row_is_selected = true;
        }
        
        index = jTable1.getSelectedRow();
        
        if(index< model.getRowCount()-1)
        {
//        model.moveRow(index, index, index-1);
        jTable1.setRowSelectionInterval(index + 1, index + 1);
        jTable1.setSelectionBackground(Color.BLACK);
        
        int SelectedRows = index+1;
        name_text_field.setText(model.getValueAt(SelectedRows, 0).toString());
        id_text_field.setText(model.getValueAt(SelectedRows, 1).toString());
        address_text_field.setText(model.getValueAt(SelectedRows, 2).toString());
         count_text_field.setText(String.valueOf(SelectedRows + 1) + " / " + model.getRowCount());
         
           
        
        }
        
    }//GEN-LAST:event_previousActionPerformed

    private void count_text_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_count_text_fieldActionPerformed
        // TODO add your handling code here:
            
    }//GEN-LAST:event_count_text_fieldActionPerformed

    private void sort_in_styleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sort_in_styleActionPerformed
        // TODO add your handling code here:
        if(sort_in_style.getSelectedItem().toString() == "Default"){
            ordr=" order by created_at asc ";
        }
        else if(sort_in_style.getSelectedItem().toString() == "Name"){
             ordr=" order by Name asc ";
        }
        else {
             ordr=" order by Id asc ";
        }
        upDateDB();
        
    }//GEN-LAST:event_sort_in_styleActionPerformed

    
    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        if(row_is_selected == false){
            model = (DefaultTableModel) jTable1.getModel();
            row_is_selected = true;
        }
        
        index = jTable1.getSelectedRow();
        
        if(index>0)
        {
//        model.moveRow(index, index, index-1);
        jTable1.setRowSelectionInterval(index - 1, index - 1);
        jTable1.setSelectionBackground(Color.BLACK);
        int SelectedRows = index-1;
        name_text_field.setText(model.getValueAt(SelectedRows, 0).toString());
        id_text_field.setText(model.getValueAt(SelectedRows, 1).toString());
        address_text_field.setText(model.getValueAt(SelectedRows, 2).toString());
         count_text_field.setText(String.valueOf(SelectedRows + 1) + " / " + model.getRowCount());
          
        }
        
        
        
        
    }//GEN-LAST:event_nextActionPerformed

    private void topActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topActionPerformed
        // TODO add your handling code here:
        
        if(row_is_selected == false){
            model = (DefaultTableModel) jTable1.getModel();
            row_is_selected = true;
        }
        index=0;
        if(model.getRowCount() > 0){
            
            jTable1.setRowSelectionInterval(index, index);
            jTable1.setSelectionBackground(Color.BLACK);
        int SelectedRows = index;
        name_text_field.setText(model.getValueAt(SelectedRows, 0).toString());
        id_text_field.setText(model.getValueAt(SelectedRows, 1).toString());
        address_text_field.setText(model.getValueAt(SelectedRows, 2).toString());
         count_text_field.setText(String.valueOf(SelectedRows + 1) + " / " + model.getRowCount());
          
        }
    }//GEN-LAST:event_topActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here;
    }//GEN-LAST:event_jTable1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_f.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_f.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_f.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_f.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_f().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JLabel address_label;
    private javax.swing.JTextField address_text_field;
    private javax.swing.JButton bottom;
    private javax.swing.JTextField count_text_field;
    private javax.swing.JButton del_btn;
    private javax.swing.JButton exit_btn;
    private javax.swing.JLabel id_label;
    private javax.swing.JTextField id_text_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel name_label;
    private javax.swing.JTextField name_text_field;
    private javax.swing.JButton next;
    private javax.swing.JButton previous;
    private javax.swing.JButton reset_btn;
    private javax.swing.JComboBox<String> sort_in_style;
    private javax.swing.JButton top;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
